{
 "title": "Ethical Dashboard",
 "time": { "from": "now-3h", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "image",
    "label": "image",
    "query": {
     "query": "container_last_seen{container_label_dappnode_dnp_dnpName!=\"\"}"
    }
   },
   { "name": "Instance", "query": { "query": "up" } }
  ]
 },
 "panels": [
  { "title": "General Stats", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "% UP dappnodes",
   "type": "timeseries",
   "gridPos": { "h": 9, "w": 13, "x": 0, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "up_percentage", "legendFormat": "UP dappnodes" }
   ]
  },
  {
   "title": "CPU Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 13, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    { "expr": "cpu_average_by_instance", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Memory Load",
   "type": "gauge",
   "gridPos": { "h": 5, "w": 3, "x": 16, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum (100 * (1 - (sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)))) / count(node_memory_MemFree_bytes * 100)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Auto updates ON",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dappmanager_auto_updates_system_packages) / count(dappmanager_auto_updates_system_packages) * 100",
     "legendFormat": "sys pkg"
    },
    {
     "expr": "sum(dappmanager_auto_updates_user_packages) / count(dappmanager_auto_updates_user_packages) * 100",
     "legendFormat": "usr pkg"
    }
   ]
  },
  {
   "title": "Total Targets",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 13, "y": 6 },
   "options": { "reduceOptions": { "calcs": [ "max" ] } },
   "targets": [
    { "expr": "count(count by(instance) (up))", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "Ethereum client ",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 16, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dappmanager_eth_fallback_enabled) / count(dappmanager_eth_fallback_enabled) * 100",
     "legendFormat": "fallback enabled"
    },
    {
     "expr": "sum(dappmanager_eth_client_target_local) / count(dappmanager_eth_client_target_local) * 100",
     "legendFormat": "local ethereum"
    }
   ]
  },
  {
   "title": "IPFS Local",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 21, "y": 6 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "sum(dappmanager_ipfs_client_target_local) / count(dappmanager_ipfs_client_target_local) * 100",
     "legendFormat": "fallback enabled"
    }
   ]
  },
  {
   "title": "CPU Load over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    { "expr": "cpu_average_by_instance", "legendFormat": "CPU" }
   ]
  },
  {
   "title": "Memory Load over time",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 10 },
   "fieldConfig": { "defaults": { "unit": "percent" } },
   "targets": [
    {
     "expr": "sum (100 * (1 - (sum(node_memory_MemFree_bytes + node_memory_Buffers_bytes + node_memory_Cached_bytes) by (instance) / sum(node_memory_MemTotal_bytes) by (instance)))) / count(node_memory_MemFree_bytes * 100)",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Staker Clients",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 18 },
   "collapsed": true,
   "panels": [
    {
     "title": "Prater Clients - Execution",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"prater\"} == 0)) / scalar(count(dappmanager_staker_config{executionClient=\"prater\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"prater\"} == 1)) / scalar(count(dappmanager_staker_config{executionClient=\"prater\"})) * 100",
       "legendFormat": "Besu"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"prater\"} == 2)) / scalar(count(dappmanager_staker_config{executionClient=\"prater\"})) * 100",
       "legendFormat": "Erigon"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"prater\"} == 3)) / scalar(count(dappmanager_staker_config{executionClient=\"prater\"})) * 100",
       "legendFormat": "Geth"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"prater\"} == 4)) / scalar(count(dappmanager_staker_config{executionClient=\"prater\"})) * 100",
       "legendFormat": "Nethermind"
      }
     ]
    },
    {
     "title": "Prater Clients - Consensus",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 12, "x": 12, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 0)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 1)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 2)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 3)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 4)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "Mainnet Clients - Execution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"} == 0)) / scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"} == 1)) / scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"})) * 100",
       "legendFormat": "Besu"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"} == 2)) / scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"})) * 100",
       "legendFormat": "Erigon"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"} == 3)) / scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"})) * 100",
       "legendFormat": "Geth"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"} == 4)) / scalar(count(dappmanager_staker_config{executionClient=\"mainnet\"})) * 100",
       "legendFormat": "Nethermind"
      }
     ]
    },
    {
     "title": "Mainnet Clients - Consensus",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 27 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"} == 0)) / scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"} == 1)) / scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"})) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"} == 2)) / scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"})) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"} == 3)) / scalar(count(dappmanager_staker_config{consensusClient=\"mainnet\"})) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"prater\"} == 4)) / scalar(count(dappmanager_staker_config{consensusClient=\"prater\"})) * 100",
       "legendFormat": "Teku"
      }
     ]
    },
    {
     "title": "Gnosis Clients - Execution",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 0, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"} == 0)) / scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"} == 1)) / scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"})) * 100",
       "legendFormat": "Besu"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"} == 2)) / scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"})) * 100",
       "legendFormat": "Erigon"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"} == 3)) / scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"})) * 100",
       "legendFormat": "Geth"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"} == 4)) / scalar(count(dappmanager_staker_config{executionClient=\"gnosis\"})) * 100",
       "legendFormat": "Nethermind"
      }
     ]
    },
    {
     "title": "Gnosis Clients - Consensus",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 12, "x": 12, "y": 34 },
     "fieldConfig": { "defaults": { "unit": "percent" } },
     "targets": [
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"} == 0)) / scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"})) * 100",
       "legendFormat": "Not configured"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"} == 1)) / scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"})) * 100",
       "legendFormat": "Lighthouse"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"} == 2)) / scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"})) * 100",
       "legendFormat": "Nimbus"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"} == 3)) / scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"})) * 100",
       "legendFormat": "Prysm"
      },
      {
       "expr": "scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"} == 4)) / scalar(count(dappmanager_staker_config{consensusClient=\"gnosis\"})) * 100",
       "legendFormat": "Teku"
      }
     ]
    }
   ]
  },
  {
   "title": "All Packages",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 19 },
   "collapsed": true,
   "panels": [
    {
     "title": "Container CPU Usage USING RECORDED RULES",
     "type": "timeseries",
     "gridPos": { "h": 12, "w": 24, "x": 0, "y": 20 },
     "fieldConfig": { "defaults": { "unit": "percentunit" } },
     "targets": [
      { "expr": "cpu_usage_total_by_container ", "legendFormat": "{{container_name}}" }
     ]
    },
    {
     "title": "Packages Installed",
     "type": "table",
     "gridPos": { "h": 8, "w": 9, "x": 0, "y": 32 },
     "targets": [
      {
       "expr": "count(container_last_seen{container_label_dappnode_dnp_dnpName!=\"\", instance=~\"$Instance\"}) by (image)",
       "legendFormat": "{{image}} - {{instance}}"
      },
      {
       "expr": "count(container_last_seen{container_label_dappnode_dnp_dnpName!=\"\", instance=~\"$Instance\"}) by (image) / scalar(count(up{service=\"\",exported_instance=\"\"}))",
       "legendFormat": "{{image}} - {{instance}}"
      }
     ]
    },
    {
     "title": "Packages Restarted last 15min",
     "type": "table",
     "gridPos": { "h": 8, "w": 7, "x": 9, "y": 32 },
     "targets": [
      {
       "expr": "count by (instance,image)(count_over_time(container_last_seen{container_label_dappnode_dnp_dnpName!=\"\", instance=~\"$Instance\"}[15m])) - 1 > 1",
       "legendFormat": "{{image}} - {{instance}}"
      }
     ]
    },
    {
     "title": "System Info",
     "type": "table",
     "gridPos": { "h": 8, "w": 8, "x": 16, "y": 32 },
     "targets": [
      {
       "expr": "cadvisor_version_info{instance=~\"$Instance\"}",
       "legendFormat": "__auto"
      }
     ]
    }
   ]
  }
 ]
}