{
 "title": "Host info",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "OS",
   "type": "piechart",
   "description": "Operating System",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (os)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Os - version",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (versionCodename)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Architectures",
   "type": "piechart",
   "description": "Number of targets by architecture",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (architecture)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Kernel",
   "type": "bargauge",
   "description": "Kernel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (kernel)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker version",
   "type": "bargauge",
   "description": "Docker server version",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (dockerServerVersion)",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Docker compose version",
   "type": "bargauge",
   "description": "Docker compose version",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_host_info{app=\"dappmanager-custom-metrics\"}) by (dockerComposeVersion)",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}