{
 "title": "Staking metrics",
 "time": { "from": "now-6h", "to": "now" },
 "templating": {
  "list": [
   { "name": "Network", "query": "mainnet,gnosis,lukso,prater" }
  ]
 },
 "panels": [
  {
   "title": "Execution and Consensus Client Stats",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 }
  },
  {
   "title": "Execution Peers - ${Network}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 1 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_rpc_exec_peers{network=\"${Network}\"}  >= 0 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Syncing nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_rpc_cons_syncing{network=\"${Network}\"}  >= 0 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Consensus Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 14, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_staker_config{consensusClient=\"${Network}\"} == 1) / count(dappmanager_staker_config{consensusClient=\"${Network}\"} > 0)",
     "legendFormat": "Lighthouse"
    },
    {
     "expr": "count(dappmanager_staker_config{consensusClient=\"${Network}\"} == 2) / count(dappmanager_staker_config{consensusClient=\"${Network}\"} > 0)",
     "legendFormat": "Nimbus"
    },
    {
     "expr": "count(dappmanager_staker_config{consensusClient=\"${Network}\"} == 3) / count(dappmanager_staker_config{consensusClient=\"${Network}\"} > 0)",
     "legendFormat": "Prysm"
    },
    {
     "expr": "count(dappmanager_staker_config{consensusClient=\"${Network}\"} == 4) / count(dappmanager_staker_config{consensusClient=\"${Network}\"} > 0)",
     "legendFormat": "Teku"
    },
    {
     "expr": "count(dappmanager_staker_config{consensusClient=\"${Network}\"} == 5) / count(dappmanager_staker_config{consensusClient=\"${Network}\"} > 0)",
     "legendFormat": "Lodestar"
    }
   ]
  },
  {
   "title": "Execution Clients",
   "type": "piechart",
   "gridPos": { "h": 8, "w": 5, "x": 19, "y": 1 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "count(dappmanager_staker_config{executionClient=\"${Network}\"} == 1) / count(dappmanager_staker_config{executionClient=\"${Network}\"} > 0)",
     "legendFormat": "Besu"
    },
    {
     "expr": "count(dappmanager_staker_config{executionClient=\"${Network}\"} == 2) / count(dappmanager_staker_config{executionClient=\"${Network}\"} > 0)",
     "legendFormat": "Erigon"
    },
    {
     "expr": "count(dappmanager_staker_config{executionClient=\"${Network}\"} == 3) / count(dappmanager_staker_config{executionClient=\"${Network}\"} > 0)",
     "legendFormat": "Geth"
    },
    {
     "expr": "count(dappmanager_staker_config{executionClient=\"${Network}\"} == 4) / count(dappmanager_staker_config{executionClient=\"${Network}\"} > 0)",
     "legendFormat": "Nethermind"
    },
    {
     "expr": "count(dappmanager_staker_config{executionClient=\"${Network}\"} == 5) / count(dappmanager_staker_config{executionClient=\"${Network}\"} > 0)",
     "legendFormat": "Nethermind"
    }
   ]
  },
  {
   "title": "Consensus Peers - ${Network}",
   "type": "stat",
   "gridPos": { "h": 4, "w": 8, "x": 0, "y": 5 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_rpc_cons_peers{network=\"${Network}\"}  >= 0 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Execution Syncing nodes",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 8, "y": 5 },
   "fieldConfig": { "defaults": { "unit": "percentunit" } },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "expr": "avg(api_rpc_exec_syncing{network=\"${Network}\"}  >= 0 )",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "Prater - LUKSO - Gnosis web3Singer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Validators over time - ${Network}",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 10 },
     "targets": [
      {
       "expr": "sum(signing_signers_loaded_count{package=\"web3signer-${Network}.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Validators - ${Network}",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 14, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(signing_signers_loaded_count{package=\"web3signer-${Network}.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Slashing protections - ${Network}",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 10 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eth2_slashingprotection_prevented_signings{package=\"web3signer-${Network}.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loaded Validators x Node - ${Network}",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 14 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(signing_signers_loaded_count{package=\"web3signer-${Network}.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signing Time - ${Network}",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 18 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (quantile)(signing_bls_signing_duration{package=\"web3signer-${Network}.dnp.dappnode.eth\"} >= 0)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Signings x second - ${Network}",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 18 },
     "targets": [
      {
       "expr": "sum(rate(signing_bls_signing_duration_count{package=\"web3signer-${Network}.dnp.dappnode.eth\"}[15m]))",
       "legendFormat": "Signings x second"
      }
     ]
    }
   ]
  },
  {
   "title": "Mainnet web3Signer Metrics",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 10 },
   "collapsed": true,
   "panels": [
    {
     "title": "Total Validators over time- mainnet",
     "type": "timeseries",
     "gridPos": { "h": 8, "w": 14, "x": 0, "y": 11 },
     "targets": [
      {
       "expr": "sum(signing_signers_loaded_count{package=\"web3signer.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Validators - mainnet",
     "type": "stat",
     "gridPos": { "h": 8, "w": 4, "x": 14, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(signing_signers_loaded_count{package=\"web3signer.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Total Slashing protections - mainnet",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 11 },
     "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
     "targets": [
      {
       "expr": "sum(eth2_slashingprotection_prevented_signings{package=\"web3signer.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Loaded Validators x Node - mainnet",
     "type": "stat",
     "gridPos": { "h": 4, "w": 6, "x": 18, "y": 15 },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg(signing_signers_loaded_count{package=\"web3signer.dnp.dappnode.eth\"})",
       "legendFormat": "__auto"
      }
     ]
    },
    {
     "title": "Signing Time - mainnet",
     "type": "bargauge",
     "gridPos": { "h": 7, "w": 10, "x": 0, "y": 19 },
     "fieldConfig": { "defaults": { "unit": "ms" } },
     "options": { "reduceOptions": { "calcs": [ "mean" ] } },
     "targets": [
      {
       "expr": "avg by (quantile)(signing_bls_signing_duration{package=\"web3signer.dnp.dappnode.eth\"} >= 0)",
       "legendFormat": "{{quantile}}"
      }
     ]
    },
    {
     "title": "Signings x second mainnet",
     "type": "timeseries",
     "gridPos": { "h": 7, "w": 14, "x": 10, "y": 19 },
     "targets": [
      {
       "expr": "sum(rate(signing_bls_signing_duration_count{package=\"web3signer.dnp.dappnode.eth\"}[15m]))",
       "legendFormat": "Signings x second"
      }
     ]
    }
   ]
  }
 ]
}