name: Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: "Release version"
        required: true

jobs:
  create_release:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.inputs.version }}
          files: |
            ethical_dashboard.json
            ethical_dashboard_aggr.json
            monitor_tor.json
            web3-staker_dashboard.json
            hostinfo_dashboard.json
          token: ${{ secrets.GITHUB_TOKEN }}
